apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "matrix-telegram-bridge.fullname" . }}-config
  labels:
    app.kubernetes.io/name:  {{ include "matrix-telegram-bridge.fullname" . }}-config
data:
  config.yaml: |-
{{ .Values.config | toYaml | indent 4 }}
