{{- $secretName := include "matrix-telegram-bridge.secretName" . }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data | default dict }}
{{- $asToken := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
{{- $hsToken := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
{{- $domain := (.Values.config.homeserver.domain | replace "." "\\.") }}

{{- if empty .Values.manualSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "matrix-telegram-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET: {{ $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET | quote }}

  MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN: {{ $asToken | quote }}
  MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN: {{ $hsToken | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "matrix-telegram-bridge.fullname" .) }}-registration
  labels:
    {{- include "matrix-telegram-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration.yaml: |
    id: "Telegram Bridge"
    as_token: {{ $asToken | b64dec | quote }}
    hs_token: {{ $hsToken | b64dec | quote }}
    namespaces:
      users:
        - exclusive: true
          {{- $username := (.Values.config.bridge.username_template | replace "{userid}" ".*") }}
          regex: '@{{- $username -}}:{{- $domain -}}'
        - exclusive: true
          regex: '@{{ .Values.config.appservice.bot_username }}:{{- $domain -}}'
      aliases:
        - exclusive: true
          {{- $alias := (.Values.config.bridge.alias_template | replace "{groupname}" ".*") }}
          regex: '\#{{- $alias -}}:{{- $domain -}}'
    url: http://{{- include "matrix-telegram-bridge.fullname" . -}}.{{- .Release.Namespace -}}.svc.cluster.local:{{- .Values.service.port }}
    sender_localpart: {{ .Values.config.appservice.bot_username | quote }}
    rate_limited: false
    de.sorunome.msc2409.push_ephemeral: true
    push_ephemeral: true
