{{- $secretName := include "matrix-telegram-bridge.secretName" . }}
{{- if empty .Values.manualSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "matrix-telegram-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data | default dict }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET: {{ $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET | quote }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN: {{ $MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN | quote }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN: {{ $MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "matrix-telegram-bridge.fullname" .) }}-registration
  labels:
    {{- include "matrix-telegram-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration.yaml: |
    {{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data | default dict }}
    id: "Telegram Bridge"
    as_token: {{ (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN") | b64dec | quote }}
    hs_token: {{ (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN") | b64dec | quote }}
    namespaces:
      users:
        - exclusive: true
          {{- $username := (.Values.config.bridge.username_template | replace "{userid}" "*") }}
          regex: "@{{- $username -}}:{{- .Values.config.homeserver.domain -}}"
        - exclusive: true
          regex: "@{{ .Values.config.appservice.bot_username }}:{{- .Values.config.homeserver.domain -}}"
      aliases:
        - exclusive: true
          {{- $alias := (.Values.config.bridge.alias_template | replace "{groupname}" "*") }}
          regex: "#{{- $alias -}}:{{- .Values.config.homeserver.domain -}}"
    url: http://{{- include "matrix-telegram-bridge.fullname" . -}}.{{- .Release.Namespace -}}.svc.cluster.local:{{- .Values.service.port }}
    sender_localpart: {{ .Values.config.appservice.bot_username | quote }}
    rate_limited: false
    de.sorunome.msc2409.push_ephemeral: true
    push_ephemeral: true