{{- if empty .Values.manualSecretName }}
{{- $secretName := include "matrix-telegram-bridge.secretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET: {{ $MAUTRIX_TELEGRAM_APPSERVICE_PROVISIONING_SHARED_SECRET | quote }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN: {{ $MAUTRIX_TELEGRAM_APPSERVICE_AS_TOKEN | quote }}

  {{- $MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN := (get $secretData "MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN") | default (randAlphaNum 64 | b64enc) }}
  MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN: {{ $MAUTRIX_TELEGRAM_APPSERVICE_HS_TOKEN | quote }}
{{- end }}
